### ISSUE TITLE
Trello Config File 

### ISSUE THREAD

**Issue by solo2424** [minfenglu/AutoGPT-PM-Plugin#2]
Can someone explain the Trello Config File? Where is this located? Do we need to make edits to it? Sorry, I just don't see anything on it.

**Comment by minfenglu** [comment]
Hi @solo2424 I have updated the [README](https://github.com/minfenglu/AutoGPT-PM-Plugin/blob/main/src/autogpt_plugins/pm_plugins/trello_plugin/READNE.md) to include instructions for the configuration file.

**Comment by solo2424** [comment]
Thanks for the quick response! That explains it perfectly.
