### ISSUE TITLE
Trello API key and Token

### ISSUE THREAD

**Issue by svallory** [minfenglu/AutoGPT-PM-Plugin#8]
I'm not familiar with Trello and I'm not sure where to get the values for the configuration. There's no API config in Trello settings, I went to Atlassian (https://id.atlassian.com/manage-profile/security/api-tokens) but they only give me a token, no key, and [Trello power-ups admin](https://trello.com/power-ups/admin/new) asks me for an [Iframe connector URL (Required for Power-Up)](https://developer.atlassian.com/cloud/trello/guides/power-ups/building-a-power-up-part-one/#:~:text=The%20most%20important%20field%20is,into%20the%20iframe%20connector%20field) which I do not have.

Can you please clarify what I'm supposed to do? Thank you so much!

**Comment by teamcoltra** [comment]
Have you read through this article? https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/

Specifically: For generating an API key, you first need to have created a Trello Power-Up. You can check our [Managing Power-Ups](https://developer.atlassian.com/cloud/trello/guides/power-ups/managing-power-ups/#adding-a-new-custom-power-up) documentation to get information on how to create your first Power-Up. Once you already have created a Power-Up, you can visit the https://trello.com/power-ups/admin page, access your Power-Up, navigate to the API Key tab and select the option Generate a new API Key.

and

For the purposes of this walkthrough, we'll have you generate a token for yourself. On the same page where you found your API key, click the hyperlinked "Token" at the right of the API key. You should be prompted with the following screen:



Your users will always see this screen when granting your application access. The permissions, duration of access, and application name displayed are all configured via the URL parameters. More on that at [Authorization](https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization). But we'll leave everything as is, and click "Allow".

Once you click Allow you'll grant your own app (identified via your API key) access to your account and be redirected to a page that contains the API token.

This token, along with your API key, can be used to read and write for your entire Trello account. Tokens should be kept secret!

**Comment by svallory** [comment]
Thank you, @teamcoltra! The first link would have been enough, I couldn't find it for some reason. But we went the extra mile as they say and made things super easy! I'll try the plugin as soon as I can.

BTW, I think you guys should add this answer to the readme. Maybe at the end, to keep the step-by-step short for those familiar with trello API, but definitely link the section or at least the link to the Atlassian docs in step 5
